sonar.projectKey=Erreur32_LogviewR
sonar.organization=erreur32

sonar.projectName=LogviewR
sonar.projectVersion=0.9.4

# Sources
sonar.sources=src,server
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.*,**/*.spec.*,**/coverage/**

# Exclude all sources from coverage (no test suite)
sonar.coverage.exclusions=**/*

# TypeScript
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
