/**
 * NewFilterModal — create a new fail2ban filter in filter.d/<name>.local.
 * Backend: POST /api/plugins/fail2ban/filters.
 * Optional duplicate-from-existing: prefills the textarea but writes a fresh .local file.
 */
import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { api } from '../../api/client';
import {
    F2bModalShell, F2bModalHeader, F2bCancelButton, F2bSaveButton,
    ResultBanner, NameInvalidHint,
    inputStyle, labelStyle, hintStyle,
} from './modalParts';

interface NewFilterModalProps {
    onClose: () => void;
    onCreated: (name: string) => void;
}

interface CreateResult {
    ok: boolean;
    name?: string;
    file?: string;
    error?: string;
}

const BLANK_TEMPLATE = `# Fail2Ban filter — generated by LogviewR
[INCLUDES]
before = common.conf

[Definition]
_daemon = my-service

# failregex: lines that mark a failure attempt
# Use <HOST> placeholder for the offending IP
failregex = ^.*your pattern with <HOST>.*$

# ignoreregex: lines that should be skipped even if they match failregex
ignoreregex =
`;

function loadFilters(setFilters: (files: string[]) => void, setLoading: (b: boolean) => void): void {
    api.get<{ ok: boolean; files: string[] }>('/api/plugins/fail2ban/filters')
        .then(res => {
            if (res.success && res.result?.ok) {
                setFilters(res.result.files.slice().sort((a, b) => a.localeCompare(b)));
            }
            setLoading(false);
        });
}

function loadFilterContent(name: string, setContent: (s: string) => void, setLoading: (b: boolean) => void): void {
    api.get<{ ok: boolean; content: string }>(`/api/plugins/fail2ban/filters/${encodeURIComponent(name)}`)
        .then(res => {
            if (res.success && res.result?.ok) setContent(res.result.content);
            setLoading(false);
        });
}

export const NewFilterModal: React.FC<NewFilterModalProps> = ({ onClose, onCreated }) => {
    const { t } = useTranslation();
    const [filters, setFilters]         = useState<string[]>([]);
    const [filtersLoading, setFiltersLoading] = useState(true);

    const [name, setName]               = useState('');
    const [duplicateFrom, setDuplicateFrom] = useState('');
    const [content, setContent]         = useState(BLANK_TEMPLATE);
    const [contentLoading, setContentLoading] = useState(false);

    const [saving, setSaving]           = useState(false);
    const [result, setResult]           = useState<CreateResult | null>(null);

    // Load existing filters for the duplicate dropdown
    useEffect(() => {
        loadFilters(setFilters, setFiltersLoading);
    }, []);

    // When duplicate source changes, fetch its content
    useEffect(() => {
        if (!duplicateFrom) return;
        setContentLoading(true);
        loadFilterContent(duplicateFrom, setContent, setContentLoading);
    }, [duplicateFrom]);

    const nameValid = /^[a-z0-9_-]{1,48}$/.test(name);
    const formValid = nameValid && content.trim() !== '';

    const submit = async () => {
        if (!formValid) return;
        setSaving(true); setResult(null);
        const res = await api.post<CreateResult>('/api/plugins/fail2ban/filters', { name, content });
        setSaving(false);
        if (res.success && res.result?.ok) {
            setResult(res.result);
            setTimeout(() => onCreated(res.result?.name ?? `${name}.local`), 800);
        } else {
            setResult({ ok: false, error: res.result?.error ?? res.error?.message ?? t('fail2ban.newFilter.errorUnknown') });
        }
    };

    const resetToBlank = () => {
        setDuplicateFrom('');
        setContent(BLANK_TEMPLATE);
    };

    const submitEnabled = formValid && !saving && result?.ok !== true;

    return (
        <F2bModalShell onClose={onClose} width="min(680px, 96vw)">
            <F2bModalHeader title={t('fail2ban.newFilter.title')} onClose={onClose} />

            {result && <ResultBanner ok={result.ok} successText={t('fail2ban.newFilter.created', { name: result.name })} errorText={result.error} />}

            {/* Body */}
            <div style={{ flex: 1, overflowY: 'auto', padding: '1rem 1.25rem' }}>

                {/* Name + duplicate-from row */}
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '.7rem', marginBottom: '.85rem' }}>
                    <div>
                        <label style={labelStyle}>{t('fail2ban.newFilter.name')}</label>
                        <input value={name} onChange={e => setName(e.target.value.toLowerCase())} placeholder="my-filter"
                            style={{ ...inputStyle, borderColor: name && !nameValid ? '#e86a65' : '#30363d' }} autoFocus />
                        <div style={hintStyle}>{t('fail2ban.newFilter.nameHint')}</div>
                    </div>
                    <div>
                        <label style={labelStyle}>{t('fail2ban.newFilter.duplicateFrom')} <span style={{ fontWeight: 400, textTransform: 'none', color: '#6e7681' }}>· {t('fail2ban.newJail.optional')}</span></label>
                        <select value={duplicateFrom} onChange={e => setDuplicateFrom(e.target.value)}
                            style={{ ...inputStyle, padding: '.32rem .5rem' }} disabled={filtersLoading}>
                            <option value="">{t('fail2ban.newFilter.blankTemplate')}</option>
                            {filters.map(f => <option key={f} value={f}>{f}</option>)}
                        </select>
                        <div style={hintStyle}>{t('fail2ban.newFilter.duplicateHint')}</div>
                    </div>
                </div>

                {/* Content */}
                <div style={{ marginBottom: '.5rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <label style={{ ...labelStyle, marginBottom: 0 }}>{t('fail2ban.newFilter.content')}</label>
                    {duplicateFrom && (
                        <button onClick={resetToBlank} style={{ fontSize: '.7rem', background: 'transparent', border: '1px solid #30363d', color: '#8b949e', borderRadius: 4, padding: '.15rem .5rem', cursor: 'pointer' }}>
                            {t('fail2ban.newFilter.resetBlank')}
                        </button>
                    )}
                </div>
                <textarea value={content} onChange={e => setContent(e.target.value)} disabled={contentLoading}
                    style={{ ...inputStyle, minHeight: 240, resize: 'vertical', lineHeight: 1.55, fontSize: '.78rem', padding: '.6rem .75rem' }} />
                <div style={hintStyle}>{t('fail2ban.newFilter.contentHint')}</div>

                {!nameValid && name && <NameInvalidHint text={t('fail2ban.newFilter.nameInvalid')} />}
            </div>

            <div style={{ padding: '.65rem 1rem', borderTop: '1px solid #30363d', display: 'flex', gap: '.5rem', justifyContent: 'space-between', alignItems: 'center', background: '#0d1117' }}>
                <span style={{ fontSize: '.7rem', color: '#6e7681', fontFamily: 'monospace' }}>
                    → filter.d/{nameValid ? name : '<name>'}.local
                </span>
                <div style={{ display: 'flex', gap: '.5rem' }}>
                    <F2bCancelButton onClick={onClose} disabled={saving} label={t('common.cancel')} />
                    <F2bSaveButton onClick={submit} enabled={submitEnabled}
                        label={saving ? t('fail2ban.newFilter.saving') : t('fail2ban.newFilter.create')} />
                </div>
            </div>
        </F2bModalShell>
    );
};
